[package]
name = "portfolio"
version = "0.1.0"
authors = ["kathleenfrench <kfrench09@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-files = "0.3"
env_logger = "0.7"
actix-http = "2"
handlebars = { version = "3.0.0", features = ["dir_source"] }
serde_json = "1.0"